let petGrammar = {
	 /*"coffeeServing" : ["with a dollop of #cream#", "as a #cream# latte", "topped with #cream# foam", "black", "as a pourover", "clover-style", "French Press", "in a teacup", "in a moka pot", "in a teapot", "in a pile of discarded Keurig cups", "with #cream#"],
    "coffeeServingInstruction" : ["Served #coffeeServing#", "Available #coffeeServing# or #coffeeServing#", "Try it #coffeeServing#", "Available #coffeeServing#"],
    "coffeeType" : ["arabica", "decaf", "mocha", "grind", "espresso", "french roast", "dark roast", "light roast", "#flavorMod# roast", "extra #flavorMod# roast"],
    
    "coffeeName" : ["#hpn# #coffeeType.capitalizeAll#", "#landscapeComplex.capitalizeAll# #coffeeType.capitalizeAll#", "#name#'s #coffeeType.capitalizeAll#"],
    "coffeeDesc" : ["#flavorAttr.capitalize#.  #coffeeServingInstruction#.", "#flavorAttr.capitalize# and #flavorAttr#.  #coffeeServingInstruction#."],*/
    "personalityAdjs" : ["untrustworthy", "unreliable", "nauseous", "adventurous", "aggressive", "loyal", "smart", "funny", "noisy", "crazy", "loud", "proud", "depressed", "happy", "quiet", "obnoxious", "skittish", "easily-distracted", "grumpy", "divine", "pleasant", "sinister", "cowardly"],
    "choiceAdjs" : ["interesting", "weird", "absurd", "amazing", "wise", "intriguing", "odd", "weird", "cool", "neat", "exotic", "peculiar"],
    "invalidChoice" : ["I've never heard of it.", "Sounds #choiceAdjs#.", "Is that #language# or something?", "What's that?", "We don't have that available."],
    "language" : ["French", "Italian", "Spanish", "Estonian", "Russian", "Polish", "Esperanto"],
    "intro" : ["Congratulations on finding a new friend! It looks like #name.capitalize# is feeling #feeling# right now. What would you like to do?"],
    "petTypes" : ["monkey", "chimpanzee", "dog", "puppy", "raccoon", "cat", "kitten", "horse", "pony", "unicorn", "cow", "water buffalo", "pig", "boar", "llama", "giraffe", "mouse", "rat", "hamster", "guinea pig", "rabbit", "bunny", "hedgehog", "chipmunk", "skunk", "badger", "turkey", "kangaroo", "bird", "duck", "parrot", "frog", "turtle", "tortoise", "lizard", "salamander", "gecko", "snake", "dragon", "sauropod", "dinosaur", "t-rex", "dolphin", "whale", "fish", "shark", "octopus", "snail", "spider", "scorpion", "crab", "lobster", "shrimp", "squid"],
    "moods" : ["playful", "excited", "happy", "hungry", "sleepy", "tired", "content", "weird", "grumpy", "sad", "lonely", "elated", "anxious", "nauseous"],
    "petNames" : ["Fido", "Alfredo", "Shredder", "Steel", "Saber", "Tex", "Rock", "Jackson", "Ace", "Knute", "Wolf", "Thorax", "Abs", "Burt", "Bret", "Duke", "Speedy", "Abby", "Admiral", "Amigo", "Astro", "Barkley", "Barnaby", "Birdie", "Bobo", "Isabelle", "Jingles", "Justice", "Courage", "Junior", "Klaus", "Kramer", "Lightning", "Monster", "Napoleon", "Snowball", "Noodles", "Nugget", "Nutmeg", "Peanut", "Phoenix", "Pickles", "Pluto", "Quincy", "Rosebud", "Sarge", "Skippy", "Snuggles", "Thor", "Truffles", "Wolfgang", "Zeus", "Zorro"]

     /*"flavorAttr" : ["#hint.a# of #flavor#", "#texture# on your tongue", "#flavorMod# and #flavorMod# as #memory#", "it is #flavorMod# and #flavorMod# as #memory#", "#flavor#, #flavor#, and #flavor# #hint.s#", "#flavorMod# #flavor#, with #hint.s# of #flavor#", "#flavor# #blendsWith# #flavorMod# #flavor#", "#flavorMod# #flavor# #blendsWith# #flavorMod# #flavor#", "#flavorMod# #flavor#", "#flavorMod# #fruit.s#", "#hint.s# of #flavorMod# #flavor#", "#flavorMod# and #flavorMod#", "#flavorMod# #flavor# #hint.s#", "it smells of #memory#", "it reminds you of  #memory#", "you smell #memory#", "you remember #memory#", "you taste #memory#", "all you can taste is #memory#", "you #areDrowningIn# #flavorMod# #flavor#"],
     "flavorMod" : ["special", "dark", "light", "bitter", "burnt", "savory", "flavorful", "aromatic", "fermented", "herbal", "pleasant", "harsh", "smoky", "sweet", "fresh", "refreshing", "somber", "bright", "perky", "sullen", "acidic", "sour", "peaty", "juicy", "perfumed", "buttery", "lush", "brisk", "strong", "weak", "tart", "tangy", "bold", "overpowering", "light", "faint", "subtle"],
    "flavor" : ["spearmint", "tobacco", "agave", "coffee", "cocoa powder", "chocolate", "sea salt", "kosher salt", "brown sugar", "cinnamon", "motor oil", "lavender", "spice", "black pepper", "cardamom", "pumpkin spice", "caramel", "toffee", "butterscotch", "peppermint", "walnut", "acid", "pear", "citrus", "grenadine", "smoke", "iodine", "coriander", "cinnamon", "acid", "salt", "sugar", "maple", "coffee", "whiskey", "regret", "sorrow", "blood", "gasoline", "grass", "cigarettes", "pine", "tar", "saltwater", "rosewater", "jasmine", "espresso", "green apple", "#fruit#", "#fruit#", "#fruit#", "#fruit#", "#fruit#"],*/

}